# Generated by Django 4.2.1 on 2023-05-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('I', 'Intermediário'), ('A', 'Avançado'), ('B', 'Básico')], default='B', max_length=1),
        ),
    ]
